name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Andrew"
      - run: |
          Write-Host "A: $env:TAG - $env:GITHUB_RUN_NUMBER"
          echo B: ${{ github.run.number }} - ${{ env.GITHUB_RUN_NUMBER }} - $env:GITHUB_RUN_NUMBER
        shell: pwsh
        env:
          TAG: $(GITHUB_RUN_NUMBER), $(github.run.number)
